version: '2'

services:

    mongo:
        image: mongo:3.4
        restart: unless-stopped
        volumes:
            - "${DATA_LOCATION}/mongo:/data/db"

    redis:
        image: redis:4-alpine
        restart: unless-stopped

    xapi:
        image: learninglocker/xapi-service:2.1.3
        restart: unless-stopped
        environment:
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - REDIS_URL=redis://redis:6379/0
            - VIRTUAL_HOST=xapi.${DOMAIN_NAME}
            - VIRTUAL_PORT=8081
            - LETSENCRYPT_HOST=xapi.${DOMAIN_NAME}
            - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
        expose:
            - 8081
        depends_on:
            - mongo
            - redis

    api:
        image: slidewiki/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - VIRTUAL_HOST=api.${DOMAIN_NAME}
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=api.${DOMAIN_NAME}
            - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
        command: "node api/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    ui:
        image: slidewiki/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
            - VIRTUAL_HOST=${DOMAIN_NAME}
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=${DOMAIN_NAME}
            - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
            - api
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"

    worker:
        image: slidewiki/learninglocker2-app:${DOCKER_TAG}
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
            - MONGO_URL=mongodb://mongo:27017/learninglocker_v2
        command: "node worker/dist/server"
        restart: unless-stopped
        depends_on:
            - mongo
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
