version: '2'

services:

    redis:
        image: redis:4-alpine
        restart: unless-stopped
        network_mode: bridge

    xapi:
        image: learninglocker/xapi-service:v1.1.0
        restart: unless-stopped
        external_links:
            - mongodb
        environment:
            - MONGO_URL
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            - redis
        network_mode: bridge
        links:
            - redis

    api:
        image: slidewiki/learninglocker2-app:${DOCKER_TAG}
        external_links:
            - mongodb
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
            - MONGO_URL
        command: "node api/dist/server"
        restart: unless-stopped
        depends_on:
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
        network_mode: bridge
        links:
            - redis

    ui:
        image: slidewiki/learninglocker2-app:${DOCKER_TAG}
        external_links:
            - mongodb
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
            - MONGO_URL
        command: "./entrypoint-ui.sh"
        restart: unless-stopped
        depends_on:
            - redis
            - api
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
        network_mode: bridge
        links:
            - redis

    worker:
        image: slidewiki/learninglocker2-app:${DOCKER_TAG}
        external_links:
            - mongodb
        environment:
            - DOMAIN_NAME
            - APP_SECRET
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_SECURED
            - SMTP_USER
            - SMTP_PASS
            - MONGO_URL
        command: "node worker/dist/server"
        restart: unless-stopped
        depends_on:
            - redis
        volumes:
            - "${DATA_LOCATION}/app-storage:/opt/learninglocker/storage"
        network_mode: bridge
        links:
            - redis
